services:

  - title: "International Conference on Machine Learning (<b>ICML</b>)"
    year: "2024, 2025, 2026"

  - title: "International Conference on Learning Representations (<b>ICLR</b>)"
    year: "2024, 2025, 2026"
    
  - title: "Neural Information Processing Systems (<b>NeurIPS</b>)"
    year: "2023, 2024, 2025"

  - title: "Association for the Advancement of Artificial Intelligence (<b>AAAI</b>)"
    year: "2025, 2026"

  - title: "Learning on Graphs Conference (<b>LoG</b>)"
    year: "2022, 2023, 2024"

  - title: "Artificial Intelligence and Statistics (<b>AISTATS</b>)"
    year: "2026"

  - title: "ACM International Conference on Information and Knowledge Management (<b>CIKM</b>)"
    year: "2024, 2025"

  - title: "ACM SIGKDD Conference on Knowledge Discovery and Data Mining (<b>KDD</b>)"
    year: "2022"

  
